# Generated by Django 6.0.6 on 2026-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('INTERVIEW', 'Interview'), ('ALGORITHM', 'Algorithm'), ('SYSTEM_DESIGN', 'System Design'), ('SQL', 'SQL'), ('BACKEND', 'backend'), ('LINUX', 'linux')], default='INTERVIEW', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20, verbose_name='Difficulty'),
        ),
    ]
