# Generated by Django 6.0.6 on 2026-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_answer_bookmark_follow_vote'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_accepted_answer',
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='post',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='cannot_follow_self',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='posts_vote_user_id_d5a95d_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('SOCIAL', 'SOCIAL MEDIA POST'), ('INTERVIEW', 'سوال مصاحبه'), ('ARTICLE', 'مقاله')], default='SOCIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='psot_type',
            field=models.CharField(choices=[('SOCIAL', 'SOCIAL MEDIA POST'), ('INTERVIEW', 'سوال مصاحبه'), ('ARTICLE', 'مقاله')], default='SOCIAL', max_length=20, verbose_name='PostType'),
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', verbose_name='Video'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='post',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
