# Generated by Django 6.0.6 on 2026-07-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_answer_unique_accepted_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='psot_type',
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('SOCIAL', 'social'), ('INTERVIEW', 'Interview'), ('ARTICLE', 'Article')], default='SOCIAL', max_length=20, verbose_name='Post Type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug'),
        ),
    ]
